### ISSUE TITLE
Add OAuth2.0 and OpenID Connect Discovery endpoints

### ISSUE THREAD

**Issue by RutsuKun** [meiling-gatekeeper/meiling#20]
https://swagger.io/docs/specification/authentication/openid-connect-discovery/

https://[base-server-url]/.well-known/openid-configuration
https://[base-server-url]/.well-known/oauth-authorization-server

**Comment by Alex4386** [comment]
> https://[base-server-url]/.well-known/openid-configuration
It was implemented by commit fbf9114.

Currently, I am implementing oauth-authorization-server endpoint.

**Comment by Alex4386** [comment]
It seems `/.well-known/oauth-authorization-server` can provide same response with openid-configuration.  
I just added alias for that at commit 886626d.
