### ISSUE TITLE
Fix misuse of term: authorization and authentication on Interfaces

### ISSUE THREAD

**Issue by Alex4386** [meiling-gatekeeper/meiling#27]
Escalated from Stella IT Community Discord.  
Reported by @Rutsukun

**Comment by RutsuKun** [comment]
Also in database

**Comment by Alex4386** [comment]
Resolving this issue brings breaking changes, including some API Endpoints.
some API endpoints e.g. `/v1/meiling/authorization` continues to work due to legacy compatibility, but this will be deprecated when Stella IT's internal migrations are complete.

**Comment by Alex4386** [comment]
Making note to myself to remove `/v1/meiling/authorization`:

https://github.com/meiling-gatekeeper/meiling/commit/0b560f8446889601df65293b712a7bcf0303de44#diff-e5a392f475668d26597be3b355c86c7395f06b50abe9b94ba08a19d049db6af7R60

**Comment by Alex4386** [comment]
ping: @Baw-Appie

**Comment by Alex4386** [comment]
> Making note to myself to remove `/v1/meiling/authorization`:
> 
> [0b560f8#diff-e5a392f475668d26597be3b355c86c7395f06b50abe9b94ba08a19d049db6af7R60](https://github.com/meiling-gatekeeper/meiling/commit/0b560f8446889601df65293b712a7bcf0303de44#diff-e5a392f475668d26597be3b355c86c7395f06b50abe9b94ba08a19d049db6af7R60)

Updated API Docs

**Comment by Alex4386** [comment]
0.8.0 fixes all of the misuse cases "that I can find" at the moment.  
And Stella IT's internal Login system is patched now. Closing Issue.
